### ISSUE TITLE
About MAP@100

### ISSUE THREAD

**Issue by yanbinbi** [neouyghur/METU_TRADEMARK_DATASET#1]
I read your paper called 《LEARNING REGIONAL ATTENTION OVER MULTI-RESOLUTION DEEP CONVOLUTIONAL FEATURES FOR TRADEMARK RETRIEVAL》 and I have some questions to ask you. The evaluation set of METU dataset has only 10 to 14 similar trademarks per group, how did you calculate MAP@100?

**Comment by neouyghur** [comment]
Hi @yanbinbi , could you read the code [here](https://github.com/neouyghur/METU-TRADEMARK-DATASET/blob/da105cfdb9ee3c83056e38ccc0c310d988a8490c/evaluation/matlab/getRankResults.m#L88)? 

Just want to remind you that MAP@100 means the mean average precision of the top 100 results.

**Comment by yanbinbi** [comment]
I know that, but in your paper, MAP@100=31.0, which means that there are, on average, 31 similar marks per class in the top 100 search results, which exceeds the number of similar trademarks contained in each group in the evaluation set

**Comment by yanbinbi** [comment]
I know that, but in your paper, MAP@100=31.0, which means that there are, on average, 31 similar trademarks per class in the top 100 search results, which exceeds the number of similar trademarks contained in each group in the evaluation set.

> Hi @yanbinbi , could you read the code [here](https://github.com/neouyghur/METU-TRADEMARK-DATASET/blob/da105cfdb9ee3c83056e38ccc0c310d988a8490c/evaluation/matlab/getRankResults.m#L88)?
> 
> Just want to remind you that MAP@100 means the mean average precision of the top 100 results.

**Comment by neouyghur** [comment]
@yanbinbi Please check the definition of MAP@100.  MAP@100=31.0 means around 31% of the expected results are listed in the top 100 results.
